# This docker-compose requires host networking, which is only available on Linux
# This compose will not function correctly on Mac or Windows
services:
  mocap_streamer_server:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
